### ISSUE TITLE
確保爬取的數據能夠被BAIFA系統統一處理

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA-web-crawling#8]
新增三張raw data資料表欄位 紀錄是否已完成解析

**Comment by TzuHanLiang** [comment]
目的是要實作數據整理，實作整理爬到數據的方法，不同鏈可以由不同的方法整理，也可以由一個方法統整所有鏈的資料的處理。

**Comment by gibbs-shih** [comment]
1. 先解決 .gitignore未正確運作
<img width="824" alt="截圖 2024-01-03 上午11 05 53" src="https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/d500c67c-9cf9-4410-b905-c13979f33d41">

2.

**Comment by gibbs-shih** [comment]
1. 新增三張raw data資料表欄位, 紀錄是否已完成解析, default: false
![截圖 2024-01-04 下午2 45 53（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/0813914c-89d1-4130-806d-708a693f3afc)

2. 更新資料欄位圖
![截圖 2024-01-04 下午2 53 35（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/7634f43a-df78-4cd8-962f-1490adb84b17)

3. 重推schema至資料庫
` npx prisma db push --schema=./prisma/schema.prisma `

**Comment by gibbs-shih** [comment]
1. 修改chains / blocks / transactions資料表, 關聯圖, 並重推至資料庫
![截圖 2024-01-05 下午2 45 39（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/dc5e8f31-5918-45e0-a7cd-c500de525afd)
![截圖 2024-01-05 下午2 45 04（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/a661854a-59ef-4b63-ab10-0c45e29b5f73)
![截圖 2024-01-05 下午3 02 57（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/525357db-66ac-4e59-b180-c33fafa9e104)

**Comment by gibbs-shih** [comment]
解析block_raw到blocks
遇到bug:
![截圖 2024-01-05 下午5 07 34 2](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/ce84a7c5-1139-496d-a38f-263ae95803aa)

**Comment by gibbs-shih** [comment]
another bug:
created_timestamp格式不正確

![截圖 2024-01-08 下午2 33 19（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/87ac3986-14e6-4a06-a3c4-2be8cbf0178c)

<img width="718" alt="截圖 2024-01-08 下午2 30 19" src="https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/873c11b1-8f21-410f-b0c2-f6fe94886cc1">


方法：將 created_timestamp改成 `created_timestamp: new Date(block.timestamp * 1000)`

**Comment by gibbs-shih** [comment]
another bug: 
Argument `size`: Invalid value provided. Expected Int, provided String.
將  `size: block.size` 改成 `size: Number(block.size)`

**Comment by gibbs-shih** [comment]
以block number 678 測試
從block_raw 到 blocks 解析成功
![截圖 2024-01-08 下午2 57 05（2）](https://github.com/CAFECA-IO/BAIFA-web-crawling/assets/73210852/8815a867-0cd0-4ed2-a944-c63f670d0e88)

**Comment by gibbs-shih** [comment]
take about 16 hr
